### ISSUE TITLE
UIUserNotificationSettings permissions only

### ISSUE THREAD

**Issue by jyounus** [jlaws/JLPermissions#19]
Hey there,

I'm trying to get this to work with UIUserNotificationSettings permissions only (I don't want/need remote notifications, just local ones). I'm using Swift, this is what I'm doing:

    JLNotificationPermission.sharedInstance().remoteNotificationType = UIRemoteNotificationType.None
    JLNotificationPermission.sharedInstance().userNotificationSettings = UIUserNotificationSettings(forTypes: UIUserNotificationType.Sound | UIUserNotificationType.Alert, categories: nil)

After that I call the authorizeWithTitle() method. If I don't allow the permission, I get the expected behaviour. But as soon as I allow system permissions, I don't get anything printed. When I check for the authorizationStatus(), it is set to JLPermissionDenied.

Any ideas what possibly needs changing?

**Comment by jlaws** [comment]
Are you testing on device? It doesn't work on simulators...

**Comment by jyounus** [comment]
I haven't tested on device, only simulator. For local notifications, the simulator works fine. 
I've fixed the issue. Required some changes to the JLNotificationPermission file. It's not the most elegant solution, but it works if you only require local notifications. I will submit a pull request sometime later on today or tomorrow.

**Comment by jlaws** [comment]
great! glad you got it working, send that PR when you get a chance

**Comment by flywww** [comment]
Have the same problem on HealthKit permission too. It even can't show the permission alert in your example code. I tried it on device not simulator.

**Comment by jlaws** [comment]
@jyounus can you send that PR?  Dont worry if it isn't elegant, I'll clean it up and get it integrated

**Comment by jyounus** [comment]
Yeah, I'll do that now. Sorry I've been busy and just didn't have the time to clean it up myself.

**Comment by jyounus** [comment]
Just submitted a PR. It needs work so it fits in with the rest of this library. Don't merge it, instead just take a look at what I did and replicate the behaviour as required in a cleaner way. You'll see what I mean when you take a look at the code.
