### ISSUE TITLE
Custom PrePremission Dialog

### ISSUE THREAD

**Issue by confile** [jlaws/JLPermissions#20]
How can I use a custom Pre-Permission Dialog?

**Comment by jlaws** [comment]
Right now the API is only setup to use Apples standard alert view.  If there is desire for a custom dialog I can see about updating the API.  Would you prefer to have it integrate something like SCLAlertView  https://github.com/vikmeup/SCLAlertView-Swift ?  Or have the user provide their own implementation of an "alert" type protocol?
