### ISSUE TITLE
Installing JLPermissions by Cocoapods will slow down the build time.

### ISSUE THREAD

**Issue by xareelee** [jlaws/JLPermissions#23]
After I installed JLPermissions via Cocoapods, building my app will be very slow. It spends lots of time on custom shell script and compiling asset catalogs every time I build (even without **build clean**).

**Comment by jlaws** [comment]
That is either a cocoapods issue or a DBPrivacyHelper issue https://github.com/danielebogo/DBPrivacyHelper

This library has no assets or custom shell scripts.
