### ISSUE TITLE
JLNotificationPermission -- needs to call [[UIApplication sharedApplication] registerForRemoteNotifications]?

### ISSUE THREAD

**Issue by kevinnguy** [jlaws/JLPermissions#29]
I was having issues grabbing the device's push token from `- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(nonnull NSData *)deviceToken` and I found out that it only worked after calling `[[UIApplication sharedApplication] registerForRemoteNotifications]`. 

Doesn't `JLNotificationPermission` need to call `[[UIApplication sharedApplication] registerForRemoteNotifications]` in order to retrieve the device's push token for remote notifications? Let me know if I'm doing this wrong. Thanks for the great work @jlaws!

**Comment by kevinnguy** [comment]
Oh, I am also working with iOS 8+

**Comment by jlaws** [comment]
Submit a PR and I will merge it and update the pod

**Comment by jlaws** [comment]
Version 2.2.8 fixes this
